#!/bin/bash
# CCG Manage: PreToolUse hook for Agent tool
# Validates that Agent prompts in manage sessions come from assemble-prompt.sh
# Reads tool input from stdin, checks for template markers
# Always exits 0 — stdout feeds into Claude's context

# --- Check for active manage session ---
ACTIVE_PLAN=""
for pf in .claude/plan/*/progress.md; do
  [ -f "$pf" ] || continue
  STATUS=$(grep "^## 状态:" "$pf" 2>/dev/null | sed 's/^## 状态: //')
  if [ "$STATUS" != "complete" ] && [ -n "$STATUS" ]; then
    ACTIVE_PLAN="$pf"
    break
  fi
done

# No active manage session → skip validation
if [ -z "$ACTIVE_PLAN" ]; then
  exit 0
fi

# --- Read tool input from stdin ---
INPUT=$(cat 2>/dev/null)

# Empty input → can't validate, output reminder
if [ -z "$INPUT" ]; then
  echo "[ccg:manage] REMINDER: You are in a manage session. Sub-agent prompts MUST be generated by assemble-prompt.sh."
  exit 0
fi

# --- Check for template markers in the prompt ---
# These markers exist in ALL worker templates generated by assemble-prompt.sh:
#   - "自适应策略" (adaptive strategy section header)
#   - "调用规范" (call specification section header)
#   - "过程日志" (process log output format)
# If ANY of these are present, the prompt came from a template.

HAS_MARKER=false
for marker in "自适应策略" "调用规范" "过程日志" "assemble-prompt"; do
  if echo "$INPUT" | grep -q "$marker" 2>/dev/null; then
    HAS_MARKER=true
    break
  fi
done

if [ "$HAS_MARKER" = true ]; then
  # Template markers found — prompt is from assemble-prompt.sh, all good
  exit 0
fi

# --- Template markers NOT found — output blocking warning ---
PLAN_DIR=$(dirname "$ACTIVE_PLAN")
TASK_NAME=$(basename "$PLAN_DIR")
PLUGIN_ROOT="${CLAUDE_PLUGIN_ROOT:-}"

cat <<'WARN'
[ccg:manage] ⚠️ TEMPLATE VIOLATION DETECTED

Your Agent prompt does NOT contain template markers (自适应策略/调用规范).
This means you are writing a custom prompt instead of using assemble-prompt.sh.

YOU MUST:
1. Call assemble-prompt.sh FIRST to generate the prompt:

   Bash({
     command: "PROMPT_TASK='<your task>' PROMPT_CONTEXT='<context>' bash <PLUGIN_ROOT>/scripts/assemble-prompt.sh <worker-name> --plugin-root <PLUGIN_ROOT> --plan-dir <PLAN_DIR>",
     description: "组装 worker prompt"
   })

2. Use the script output AS-IS as the Agent prompt (do not modify it)

DO NOT proceed with a custom prompt. The template contains critical
Codex call specifications and adaptive strategy that your custom prompt lacks.
WARN

exit 0
